/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_e68f4b01 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/ysrqvncsrnoyeqbrgdil/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "@supabase/supabase-js";
import dotenv from "dotenv";
import path from "path";

// Load environment variables from root
try {
  dotenv.config({ path: path.resolve(process.cwd(), "../.env") });
} catch (e) {
  console.log("Could not load .env file");
}

// In-memory fallback store
const memoryStore = new Map<string, any>();

const client = () => {
  const url = process.env.SUPABASE_URL;
  // Try Service Role Key first, then fall back to Anon Key (SUPABASE_KEY)
  const key =
    process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_KEY;

  if (!url || !key) return null;
  return createClient(url, key, {
    db: { schema: "public" },
  });
};

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client();
  if (!supabase) {
    console.log(`[KV Mock] Setting ${key}`);
    memoryStore.set(key, value);
    return;
  }

  // If it is an order, save to the 'orders' table
  if (key.startsWith("ord_")) {
    const { error } = await supabase.from("orders").upsert({
      id: value.id,
      network: value.network,
      bundle_data: value.bundleData,
      amount: value.bundlePrice,
      recipient_number: value.recipientNumber,
      payment_number: value.paymentNumber,
      email: value.email || null,
      status: value.status,
      created_at: value.createdAt,
    });
    if (error) {
      console.error("SUPABASE ERROR:", JSON.stringify(error, null, 2));
      // Fallback to memory so app doesn't crash during demo
      console.log(
        `[KV Mock Fallback] Setting ${key} in memory because Supabase failed.`,
      );
      memoryStore.set(key, value);
      return;
    }
    return;
  }

  // Fallback to KV
  const { error } = await supabase.from("kv_store_e68f4b01").upsert({
    key,
    value,
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a value from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client();
  if (!supabase) {
    console.log(`[KV Mock] Getting ${key}`);
    return memoryStore.get(key);
  }

  // Use the REAL 'orders' table if looking for an order
  if (key.startsWith("ord_")) {
    const { data, error } = await supabase
      .from("orders")
      .select("*")
      .eq("id", key)
      .single();

    if (error) {
      if (error.code === "PGRST116") return null;
      throw new Error(error.message);
    }

    // Map Snake_Case DB to CamelCase App
    return {
      id: data.id,
      network: data.network,
      bundleData: data.bundle_data,
      bundlePrice: data.amount,
      recipientNumber: data.recipient_number,
      paymentNumber: data.payment_number,
      email: data.email,
      status: data.status,
      createdAt: data.created_at,
    };
  }

  // Fallback to KV for other things
  const { data, error } = await supabase
    .from("kv_store_e68f4b01")
    .select("value")
    .eq("key", key)
    .single();

  if (error) {
    if (error.code === "PGRST116") return null;
    throw new Error(error.message);
  }
  return data?.value;
};

// Get by Prefix
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client();
  if (!supabase) {
    return Array.from(memoryStore.entries())
      .filter(([k]) => k.startsWith(prefix))
      .map(([_, v]) => v);
  }

  // If asking for orders, get from 'orders' table
  if (prefix === "ord_") {
    const { data, error } = await supabase
      .from("orders")
      .select("*")
      .order("created_at", { ascending: false });

    if (error) {
      console.error("Error fetching orders:", error);
      // Return empty array instead of crashing if table doesn't exist
      return [];
    }

    // Map back to the format the frontend expects (camelCase)
    return data.map((row) => ({
      id: row.id,
      network: row.network,
      bundleId: row.bundle_data, // Using bundle_data as ID for display if needed, or mapped purely for display
      bundleData: row.bundle_data,
      bundlePrice: row.amount,
      recipientNumber: row.recipient_number,
      paymentNumber: row.payment_number,
      status: row.status,
      createdAt: row.created_at,
      email: row.email,
    }));
  }

  const { data, error } = await supabase
    .from("kv_store_e68f4b01")
    .select("key, value")
    .like("key", `${prefix}%`);

  if (error) throw new Error(error.message);

  return data?.map((row: any) => row.value) || [];
};

// Delete
export const del = async (key: string): Promise<void> => {
  const supabase = client();
  if (!supabase) {
    memoryStore.delete(key);
    return;
  }
  const { error } = await supabase
    .from("kv_store_e68f4b01")
    .delete()
    .eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};
