/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nmvckqlrqkxozgoicgaw";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tdmNrcWxycWt4b3pnb2ljZ2F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyMTUzNTEsImV4cCI6MjA4NDc5MTM1MX0.n099kL_gNR_cQWhC6sFfQwkw4pZ6bh8oEzIx3Ax4A2M";
